batch_size: [32] # 64
epochs: 100
lr: [1.0e-3, 1.0e-2]
latent_dim: [512] # 1024
projector_dim: [32] # 64, 128
num_cv_folds: 5
num_cv_bins: 10
scaffold_split_val_sz : 0.1
task: "antiviral-potency"
repr_type: "ECFP"
