task: "admet"
target_task: ["MLM", "HLM", "KSOL", "LogD", "MDR1-MDCKII"]

# Learning params
batch_size: [32]
epochs: 500
lr: [1.0e-3]

# Cross validation params
num_cv_folds: 5
num_cv_bins: 10
scaffold_split_val_sz : 0.1

# Representation model params
repr_model: "ECFP"
radius: [2]
out_channels: [1024]

# Projection head model params
# latent_dim: *out_channels
proj_hidden_dim: [64]
out_dim: 1
