task: "potency"
target_task: ["pIC50 (MERS-CoV Mpro)" , "pIC50 (SARS-CoV-2 Mpro)"]

# Learning params
batch_size: [16, 32] #, 64]
epochs: 500
# lr: [1.0e-5, 1.0e-4, 1.0e-3]
lr: [1.0e-3]
weight_decay: [0.0] #, 1.0e-4, 1.0e-5]

# Cross validation params
num_cv_folds: 5
num_cv_bins: 10
scaffold_split_val_sz : 0.1

# Representation model params
repr_model: "ECFP"
radius: [2, 3]
out_channels: [1024, 2048]

# Projection head model params
# latent_dim: *out_channels
proj_hidden_dim: [64, 128] #, 256]
out_dim: 1
