task: "antiviral-potency"

# Learning params
batch_size: 32
epochs: 100
lr: 1.0e-3

# Cross validation params
num_cv_folds: 5
num_cv_bins: 10
scaffold_split_val_sz : 0.1

# Representation model params
repr_model: "GIN"
in_channels: 9
hidden_channels: 64
out_channels: &out_channels 128
num_layers: 3
dropout: 0.01

# Projection head model params
latent_dim: *out_channels
out_dim: 1
