task: "potency"
target_task: ["pIC50 (MERS-CoV Mpro)" , "pIC50 (SARS-CoV-2 Mpro)"]

# Learning params
batch_size: [32, 64]
epochs: 200
lr: [1.0e-3, 1.0e-4]

# Cross validation params
num_cv_folds: 5
num_cv_bins: 10
scaffold_split_val_sz : 0.1

# Representation model params
repr_model: ["GIN"] #, "GAT", "GCN", "GraphSAGE"]
in_channels: 9
hidden_channels: [32, 64]
out_channels: [64, 128]
num_layers: [2, 3]
dropout: [0.1, 0.3]

# Projection head model params
# latent_dim: *out_channels
proj_hidden_dim: [64]
out_dim: 1
