batch_size: [32, 64]
epochs: 200
lr: [1e-3, 1e-2]
latent_dim: [256, 512, 1024]
projector_dim: [16, 32, 64, 128]
num_cv_folds: 10
num_cv_bins: 10
scaffold_split_val_sz : 0.1
task: "potency"
repr_type: "ECFP"
